name: 'Zodash Open Terminal'
description: 'open terminal with github action'
author: 'Zero <GitHub: whatwewant>'
branding:
  icon: 'message-square'
  color: 'green'
color:
inputs:
  code:
    required: false
    description: custom server code
  relay:
    required: false
    description: custom server relay
  report_url:
    required: false
    description: online report url
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: docker
  image: Dockerfile
  # entrypoint: 'sh -c'
  # args:
  #   - node /app/lib/action.js
  env:
    CODE: ${{ inputs.code }}
    RELAY: ${{ inputs.relay }}
    REPORT_URL: ${{ inputs.report_url }}
