name: 'Zodash Open Terminal'
description: 'open terminal with github action'
author: 'Zero <GitHub: whatwewant>'
branding:
  icon: 'message-square'
  color: 'green'
color:
inputs:
  name:
    required: false
    description: the msg metion to
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: docker
  image: Dockerfile
  # entrypoint: 'sh -c'
  # args:
  #   - node /app/lib/action.js
  env:
    ACTION_NAME: ${{ inputs.name }}
